###############################################################################
# Created by write_sdc
###############################################################################
current_design S_term_DSP
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name UserCLK -period 20.0000 [get_ports {UserCLK}]
set_clock_transition 0.1500 [get_clocks {UserCLK}]
set_clock_uncertainty 0.2500 UserCLK
set_propagated_clock [get_clocks {UserCLK}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[0]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[10]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[11]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[12]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[13]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[14]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[15]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[16]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[17]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[18]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[19]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[1]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[20]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[21]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[22]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[23]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[24]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[25]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[26]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[27]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[28]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[29]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[2]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[30]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[31]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[3]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[4]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[5]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[6]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[7]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[8]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData[9]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[0]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[10]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[11]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[12]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[13]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[14]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[15]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[16]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[17]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[18]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[19]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[1]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[2]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[3]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[4]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[5]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[6]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[7]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[8]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe[9]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S1END[0]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S1END[1]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S1END[2]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S1END[3]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2END[0]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2END[1]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2END[2]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2END[3]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2END[4]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2END[5]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2END[6]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2END[7]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2MID[0]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2MID[1]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2MID[2]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2MID[3]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2MID[4]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2MID[5]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2MID[6]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S2MID[7]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[0]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[10]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[11]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[12]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[13]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[14]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[15]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[1]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[2]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[3]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[4]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[5]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[6]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[7]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[8]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {S4END[9]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[0]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[10]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[11]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[12]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[13]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[14]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[15]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[1]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[2]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[3]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[4]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[5]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[6]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[7]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[8]}]
set_input_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {SS4END[9]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[0]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[10]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[11]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[12]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[13]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[14]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[15]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[16]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[17]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[18]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[19]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[1]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[20]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[21]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[22]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[23]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[24]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[25]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[26]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[27]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[28]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[29]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[2]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[30]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[31]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[3]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[4]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[5]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[6]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[7]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[8]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameData_O[9]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[0]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[10]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[11]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[12]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[13]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[14]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[15]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[16]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[17]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[18]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[19]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[1]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[2]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[3]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[4]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[5]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[6]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[7]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[8]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {FrameStrobe_O[9]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N1BEG[0]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N1BEG[1]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N1BEG[2]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N1BEG[3]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEG[0]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEG[1]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEG[2]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEG[3]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEG[4]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEG[5]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEG[6]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEG[7]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEGb[0]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEGb[1]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEGb[2]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEGb[3]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEGb[4]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEGb[5]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEGb[6]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N2BEGb[7]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[0]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[10]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[11]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[12]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[13]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[14]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[15]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[1]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[2]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[3]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[4]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[5]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[6]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[7]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[8]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {N4BEG[9]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[0]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[10]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[11]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[12]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[13]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[14]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[15]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[1]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[2]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[3]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[4]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[5]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[6]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[7]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[8]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {NN4BEG[9]}]
set_output_delay 4.0000 -clock [get_clocks {UserCLK}] -add_delay [get_ports {UserCLKo}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0060 [get_ports {UserCLKo}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[31]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[30]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[29]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[28]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[27]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[26]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[25]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[24]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[23]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[22]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[21]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[20]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[19]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[18]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[17]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[16]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[15]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[14]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[13]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[12]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[11]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[10]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[9]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[8]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[7]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[6]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[5]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[4]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[3]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[2]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[1]}]
set_load -pin_load 0.0060 [get_ports {FrameData_O[0]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[19]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[18]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[17]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[16]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[15]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[14]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[13]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[12]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[11]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[10]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[9]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[8]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[7]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[6]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[5]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[4]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[3]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[2]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[1]}]
set_load -pin_load 0.0060 [get_ports {FrameStrobe_O[0]}]
set_load -pin_load 0.0060 [get_ports {N1BEG[3]}]
set_load -pin_load 0.0060 [get_ports {N1BEG[2]}]
set_load -pin_load 0.0060 [get_ports {N1BEG[1]}]
set_load -pin_load 0.0060 [get_ports {N1BEG[0]}]
set_load -pin_load 0.0060 [get_ports {N2BEG[7]}]
set_load -pin_load 0.0060 [get_ports {N2BEG[6]}]
set_load -pin_load 0.0060 [get_ports {N2BEG[5]}]
set_load -pin_load 0.0060 [get_ports {N2BEG[4]}]
set_load -pin_load 0.0060 [get_ports {N2BEG[3]}]
set_load -pin_load 0.0060 [get_ports {N2BEG[2]}]
set_load -pin_load 0.0060 [get_ports {N2BEG[1]}]
set_load -pin_load 0.0060 [get_ports {N2BEG[0]}]
set_load -pin_load 0.0060 [get_ports {N2BEGb[7]}]
set_load -pin_load 0.0060 [get_ports {N2BEGb[6]}]
set_load -pin_load 0.0060 [get_ports {N2BEGb[5]}]
set_load -pin_load 0.0060 [get_ports {N2BEGb[4]}]
set_load -pin_load 0.0060 [get_ports {N2BEGb[3]}]
set_load -pin_load 0.0060 [get_ports {N2BEGb[2]}]
set_load -pin_load 0.0060 [get_ports {N2BEGb[1]}]
set_load -pin_load 0.0060 [get_ports {N2BEGb[0]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[15]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[14]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[13]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[12]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[11]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[10]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[9]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[8]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[7]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[6]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[5]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[4]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[3]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[2]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[1]}]
set_load -pin_load 0.0060 [get_ports {N4BEG[0]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[15]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[14]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[13]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[12]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[11]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[10]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[9]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[8]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[7]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[6]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[5]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[4]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[3]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[2]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[1]}]
set_load -pin_load 0.0060 [get_ports {NN4BEG[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {UserCLK}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[31]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[30]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[29]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[28]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[27]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[26]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[25]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[24]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[23]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[22]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[21]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[20]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[19]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[18]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[17]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[16]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[15]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[14]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[13]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[12]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[11]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[10]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[9]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[8]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameData[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[19]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[18]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[17]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[16]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[15]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[14]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[13]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[12]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[11]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[10]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[9]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[8]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {FrameStrobe[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S1END[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S1END[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S1END[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S1END[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2END[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2END[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2END[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2END[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2END[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2END[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2END[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2END[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2MID[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2MID[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2MID[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2MID[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2MID[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2MID[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2MID[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S2MID[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[15]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[14]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[13]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[12]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[11]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[10]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[9]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[8]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {S4END[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[15]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[14]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[13]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[12]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[11]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[10]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[9]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[8]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SS4END[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
