build_all:
	cd all_ones; make
	cd all_zeros; make
	cd counter; make
	cd counter_top; make
	cd custom_instruction; make
	cd custom_instruction_and_peripheral; make
	cd passthrough; make
	cd sram; make
	cd bram; make
	cd peripheral; make
	cd peripheral_sram; make
	cd trigger_slot0; make
	cd trigger_slot1; make
	cd trigger_irq; make
	cd serv; make
	cd fazyrv; make
.PHONY: build_all

clean_all:
	cd all_ones; make clean
	cd all_zeros; make clean
	cd counter; make clean
	cd counter_top; make clean
	cd custom_instruction; make clean
	cd custom_instruction_and_peripheral; make clean
	cd passthrough; make clean
	cd sram; make clean
	cd bram; make clean
	cd peripheral; make clean
	cd peripheral_sram; make clean
	cd trigger_slot0; make clean
	cd trigger_slot1; make clean
	cd trigger_irq; make clean
	cd serv; make clean
	cd fazyrv; make clean
.PHONY: clean_all
