# Paths
FABULOUS_ROOT = ../../macro/ihp-sg13g2/fabulous
EXTRA_PRIMITIVES_PATH = ../extra_primitives.v
BIT_GEN = ../bit_gen.py
BIT_TO_HEX = ../bit_to_hex.py

# Adjust sources
RTL = ../top_wrapper.v top.sv $(wildcard rtl/*.sv) $(wildcard rtl/*.v) ../primitive_wrappers.v
TOP = top_wrapper
DESIGN_NAME = fazyrv

# Include base Makefile
include ../makefile.include
