meta:
  version: 2
  flow: FABulousTile

FABULOUS_TILE_DIR: dir::. #tiles/S_term_IHP_SRAM

# Basics
DESIGN_NAME: S_term_IHP_SRAM
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: UserCLK

# Area
FP_SIZING: absolute
pdk::ihp-sg13g2:
    # Width should be multiple of 0.48 (Metal2 pitch)
    # Height should be multiple of 0.42 (Metal3 pitch)
    DIE_AREA: [0, 0, 109.44, 53.76]
    PL_TARGET_DENSITY_PCT: 96
