// Auto-generated by LibreLane
module S_CPU_IRQ(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  output[3:0] N1BEG,
  output[7:0] N2BEG,
  output[7:0] N2BEGb,
  output[15:0] N4BEG,
  output[15:0] NN4BEG,
  output Co,
  input[3:0] S1END,
  input[7:0] S2MID,
  input[7:0] S2END,
  input[15:0] S4END,
  input[15:0] SS4END,
  input CONFIGURED_top,
  output IRQ_top0,
  output IRQ_top1,
  output IRQ_top2,
  output IRQ_top3,
  input UserCLK,
  output UserCLKo,
  input[31:0] FrameData,
  output[31:0] FrameData_O,
  input[19:0] FrameStrobe,
  output[19:0] FrameStrobe_O
);
endmodule
