// Auto-generated by LibreLane
module N_term_single(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[3:0] N1END,
  input[7:0] N2MID,
  input[7:0] N2END,
  input[15:0] N4END,
  input[15:0] NN4END,
  input Ci,
  output[3:0] S1BEG,
  output[7:0] S2BEG,
  output[7:0] S2BEGb,
  output[15:0] S4BEG,
  output[15:0] SS4BEG,
  input UserCLK,
  output UserCLKo,
  input[31:0] FrameData,
  output[31:0] FrameData_O,
  input[19:0] FrameStrobe,
  output[19:0] FrameStrobe_O
);
endmodule
