meta:
  version: 2
  flow: FABulousFabric
  substituting_steps:
    # Save some time
    Magic.DRC: null
    #KLayout.DRC: null

    # Add steps for LVS with KLayout
    #+Checker.LVS: OpenROAD.WriteCDL
    #+OpenROAD.WriteCDL: KLayout.LVS
    
    # The new version of OpenROAD says
    # during DPL it needs stdcell rows
    # (although we don't use stdcells)
    #OpenROAD.DetailedPlacement: null

# Basics
DESIGN_NAME: eFPGA
VERILOG_FILES: []

# No extract-unique, because the power straps
# are connected in the top-level integration
MAGIC_NO_EXT_UNIQUE: true

# Unfortunately needed
GRT_ALLOW_CONGESTION: true

# FABulous config
FABULOUS_FABRIC_CONFIG: dir::fabric.csv
FABULOUS_TILE_LIBRARY: dir::../tile_library/tiles/

FABULOUS_TILE_SPACING: 0
# Vertical spacing should be multiple of 0.42 (Metal2 pitch)
# Horizontal spacing should be multiple of 0.48 (Metal3 pitch)
# The halo was chosen so that there's just enough space for the pins
# except for the bottom: here the clock net needs to be routed
FABULOUS_HALO_SPACING: [ 0.48, 4.2, 0.48, 0.48 ]

# Match spacing if possible
IO_PIN_H_LENGTH: 0.48
IO_PIN_V_LENGTH: 0.48

FABULOUS_TILE_SIZES:
  LUT4AB:           [ 215.04, 215.46 ]
  
  "IHP_SRAM_*":     [ 109.44, 215.46 ]
  "IHP_BRAM_*":     [ 109.44, 215.46 ]
  "*term_IHP_SRAM": [ 109.44, 53.76]

  RegFile:          [ 239.04, 215.46 ]
  "*_term_single2": [ 239.04, 53.76 ]
 
  "DSP*":           [ 184.8, 215.46 ]
  "*term_DSP*":     [ 184.8, 53.76 ]

  "W_IO":           [ 107.52, 215.46 ]
  "N*":             [ 215.04, 53.76 ]
  "S*":             [ 215.04, 53.76 ]

# Save on file space by sharing same cells
PRIMARY_GDSII_STREAMOUT_TOOL: klayout
#KLAYOUT_CONFLICT_RESOLUTION: SkipNewCell

# The pin placer tool has a default min distance between pins of 2 routing tracks.
# Allow to place pins everywhere on the routing grid.
IO_PIN_MIN_DISTANCE: 0.42 # horizontal grid distance

# Manual pin placement to prevent congestion
FABULOUS_MANUAL_PINS:
    "UserCLK": [Metal2, 5.76, 0.24, 0.4, 0.48]

    "FrameStrobe[0]": [Metal2, 10.56, 0.24, 0.4, 0.48]
    "FrameStrobe[1]": [Metal2, 15.36, 0.24, 0.4, 0.48]
    "FrameStrobe[2]": [Metal2, 20.16, 0.24, 0.4, 0.48]
    "FrameStrobe[3]": [Metal2, 24.96, 0.24, 0.4, 0.48]
    "FrameStrobe[4]": [Metal2, 29.76, 0.24, 0.4, 0.48]
    "FrameStrobe[5]": [Metal2, 34.56, 0.24, 0.4, 0.48]
    "FrameStrobe[6]": [Metal2, 39.36, 0.24, 0.4, 0.48]
    "FrameStrobe[7]": [Metal2, 44.16, 0.24, 0.4, 0.48]
    "FrameStrobe[8]": [Metal2, 48.96, 0.24, 0.4, 0.48]
    "FrameStrobe[9]": [Metal2, 53.76, 0.24, 0.4, 0.48]
    "FrameStrobe[10]": [Metal2, 58.56, 0.24, 0.4, 0.48]
    "FrameStrobe[11]": [Metal2, 63.36, 0.24, 0.4, 0.48]
    "FrameStrobe[12]": [Metal2, 68.16, 0.24, 0.4, 0.48]
    "FrameStrobe[13]": [Metal2, 72.96, 0.24, 0.4, 0.48]
    "FrameStrobe[14]": [Metal2, 77.76, 0.24, 0.4, 0.48]
    "FrameStrobe[15]": [Metal2, 82.56, 0.24, 0.4, 0.48]
    "FrameStrobe[16]": [Metal2, 87.36, 0.24, 0.4, 0.48]
    "FrameStrobe[17]": [Metal2, 92.16, 0.24, 0.4, 0.48]
    "FrameStrobe[18]": [Metal2, 96.96, 0.24, 0.4, 0.48]
    "FrameStrobe[19]": [Metal2, 101.76, 0.24, 0.4, 0.48]

    "FrameStrobe[220]": [Metal2, 2262.24, 0.24, 0.4, 0.48]
    "FrameStrobe[221]": [Metal2, 2267.04, 0.24, 0.4, 0.48]
    "FrameStrobe[222]": [Metal2, 2271.84, 0.24, 0.4, 0.48]
    "FrameStrobe[223]": [Metal2, 2276.64, 0.24, 0.4, 0.48]
    "FrameStrobe[224]": [Metal2, 2281.44, 0.24, 0.4, 0.48]
    "FrameStrobe[225]": [Metal2, 2286.24, 0.24, 0.4, 0.48]
    "FrameStrobe[226]": [Metal2, 2291.04, 0.24, 0.4, 0.48]
    "FrameStrobe[227]": [Metal2, 2295.84, 0.24, 0.4, 0.48]
    "FrameStrobe[228]": [Metal2, 2300.64, 0.24, 0.4, 0.48]
    "FrameStrobe[229]": [Metal2, 2305.44, 0.24, 0.4, 0.48]
    "FrameStrobe[230]": [Metal2, 2310.24, 0.24, 0.4, 0.48]
    "FrameStrobe[231]": [Metal2, 2315.04, 0.24, 0.4, 0.48]
    "FrameStrobe[232]": [Metal2, 2319.84, 0.24, 0.4, 0.48]
    "FrameStrobe[233]": [Metal2, 2324.64, 0.24, 0.4, 0.48]
    "FrameStrobe[234]": [Metal2, 2329.44, 0.24, 0.4, 0.48]
    "FrameStrobe[235]": [Metal2, 2334.24, 0.24, 0.4, 0.48]
    "FrameStrobe[236]": [Metal2, 2339.04, 0.24, 0.4, 0.48]
    "FrameStrobe[237]": [Metal2, 2343.84, 0.24, 0.4, 0.48]
    "FrameStrobe[238]": [Metal2, 2348.64, 0.24, 0.4, 0.48]
    "FrameStrobe[239]": [Metal2, 2353.44, 0.24, 0.4, 0.48]

    "FrameData[0]": [Metal3, 0.24, 3505.74, 0.48, 0.4]
    "FrameData[1]": [Metal3, 0.24, 3507.42, 0.48, 0.4]
    "FrameData[2]": [Metal3, 0.24, 3509.10, 0.48, 0.4]
    "FrameData[3]": [Metal3, 0.24, 3510.78, 0.48, 0.4]
    "FrameData[4]": [Metal3, 0.24, 3512.46, 0.48, 0.4]
    "FrameData[5]": [Metal3, 0.24, 3514.14, 0.48, 0.4]
    "FrameData[6]": [Metal3, 0.24, 3515.82, 0.48, 0.4]
    "FrameData[7]": [Metal3, 0.24, 3517.50, 0.48, 0.4]
    "FrameData[8]": [Metal3, 0.24, 3519.18, 0.48, 0.4]
    "FrameData[9]": [Metal3, 0.24, 3520.86, 0.48, 0.4]
    "FrameData[10]": [Metal3, 0.24, 3522.54, 0.48, 0.4]
    "FrameData[11]": [Metal3, 0.24, 3524.22, 0.48, 0.4]
    "FrameData[12]": [Metal3, 0.24, 3525.90, 0.48, 0.4]
    "FrameData[13]": [Metal3, 0.24, 3527.58, 0.48, 0.4]
    "FrameData[14]": [Metal3, 0.24, 3529.26, 0.48, 0.4]
    "FrameData[15]": [Metal3, 0.24, 3530.94, 0.48, 0.4]
    "FrameData[16]": [Metal3, 0.24, 3532.62, 0.48, 0.4]
    "FrameData[17]": [Metal3, 0.24, 3534.30, 0.48, 0.4]
    "FrameData[18]": [Metal3, 0.24, 3535.98, 0.48, 0.4]
    "FrameData[19]": [Metal3, 0.24, 3537.66, 0.48, 0.4]
    "FrameData[20]": [Metal3, 0.24, 3539.34, 0.48, 0.4]
    "FrameData[21]": [Metal3, 0.24, 3541.02, 0.48, 0.4]
    "FrameData[22]": [Metal3, 0.24, 3542.70, 0.48, 0.4]
    "FrameData[23]": [Metal3, 0.24, 3544.38, 0.48, 0.4]
    "FrameData[24]": [Metal3, 0.24, 3546.06, 0.48, 0.4]
    "FrameData[25]": [Metal3, 0.24, 3547.74, 0.48, 0.4]
    "FrameData[26]": [Metal3, 0.24, 3549.42, 0.48, 0.4]
    "FrameData[27]": [Metal3, 0.24, 3551.10, 0.48, 0.4]
    "FrameData[28]": [Metal3, 0.24, 3552.78, 0.48, 0.4]
    "FrameData[29]": [Metal3, 0.24, 3554.46, 0.48, 0.4]
    "FrameData[30]": [Metal3, 0.24, 3556.14, 0.48, 0.4]
    "FrameData[31]": [Metal3, 0.24, 3557.82, 0.48, 0.4]

    "FrameData[544]": [Metal3, 0.24, 4.62, 0.48, 0.4]
    "FrameData[545]": [Metal3, 0.24, 6.30, 0.48, 0.4]
    "FrameData[546]": [Metal3, 0.24, 7.98, 0.48, 0.4]
    "FrameData[547]": [Metal3, 0.24, 9.66, 0.48, 0.4]
    "FrameData[548]": [Metal3, 0.24, 11.34, 0.48, 0.4]
    "FrameData[549]": [Metal3, 0.24, 13.02, 0.48, 0.4]
    "FrameData[550]": [Metal3, 0.24, 14.70, 0.48, 0.4]
    "FrameData[551]": [Metal3, 0.24, 16.38, 0.48, 0.4]
    "FrameData[552]": [Metal3, 0.24, 18.06, 0.48, 0.4]
    "FrameData[553]": [Metal3, 0.24, 19.74, 0.48, 0.4]
    "FrameData[554]": [Metal3, 0.24, 21.42, 0.48, 0.4]
    "FrameData[555]": [Metal3, 0.24, 23.10, 0.48, 0.4]
    "FrameData[556]": [Metal3, 0.24, 24.78, 0.48, 0.4]
    "FrameData[557]": [Metal3, 0.24, 26.46, 0.48, 0.4]
    "FrameData[558]": [Metal3, 0.24, 28.14, 0.48, 0.4]
    "FrameData[559]": [Metal3, 0.24, 29.82, 0.48, 0.4]
    "FrameData[560]": [Metal3, 0.24, 31.50, 0.48, 0.4]
    "FrameData[561]": [Metal3, 0.24, 33.18, 0.48, 0.4]
    "FrameData[562]": [Metal3, 0.24, 34.86, 0.48, 0.4]
    "FrameData[563]": [Metal3, 0.24, 36.54, 0.48, 0.4]
    "FrameData[564]": [Metal3, 0.24, 38.22, 0.48, 0.4]
    "FrameData[565]": [Metal3, 0.24, 39.90, 0.48, 0.4]
    "FrameData[566]": [Metal3, 0.24, 41.58, 0.48, 0.4]
    "FrameData[567]": [Metal3, 0.24, 43.26, 0.48, 0.4]
    "FrameData[568]": [Metal3, 0.24, 44.94, 0.48, 0.4]
    "FrameData[569]": [Metal3, 0.24, 46.62, 0.48, 0.4]
    "FrameData[570]": [Metal3, 0.24, 48.30, 0.48, 0.4]
    "FrameData[571]": [Metal3, 0.24, 49.98, 0.48, 0.4]
    "FrameData[572]": [Metal3, 0.24, 51.66, 0.48, 0.4]
    "FrameData[573]": [Metal3, 0.24, 53.34, 0.48, 0.4]
    "FrameData[574]": [Metal3, 0.24, 55.02, 0.48, 0.4]
    "FrameData[575]": [Metal3, 0.24, 56.70, 0.48, 0.4]

    
# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: UserCLK

# Routing
RT_CLOCK_MAX_LAYER: TopMetal1
RT_MAX_LAYER: TopMetal1
DRT_MAX_LAYER: TopMetal1

# Disable stdcells
#SYNTH_ELABORATE_ONLY: true
RUN_POST_GPL_DESIGN_REPAIR: false
RUN_POST_CTS_RESIZER_TIMING: false
DESIGN_REPAIR_BUFFER_INPUT_PORTS: false
PDN_ENABLE_RAILS: false
RUN_ANTENNA_REPAIR: false
RUN_FILL_INSERTION: false
RUN_TAP_ENDCAP_INSERTION: false
RUN_CTS: false
RUN_IRDROP_REPORT: false
ERROR_ON_SYNTH_CHECKS: false

# PDN (of the tiles) TODO
# Needs to be the same PDN setting as for the tiles
# as it is used to overly vertical power straps
# at the same position as at the tiles
PDN_VERTICAL_LAYER: TopMetal1
PDN_HORIZONTAL_LAYER: TopMetal2

PDN_VWIDTH: 2.2
PDN_VSPACING: 4.0
PDN_VPITCH: 75.6
PDN_VOFFSET: 13.6

PDN_HWIDTH: 2.0
PDN_HSPACING: 4.0
PDN_HPITCH: 75.6
PDN_HOFFSET: 13.57

VDD_PIN: VPWR
GND_PIN: VGND
