# Paths
FABULOUS_ROOT = ../../macro/ihp-sg13g2/fabulous
EXTRA_PRIMITIVES_PATH = ../extra_primitives.v
BIT_GEN = ../bit_gen.py
BIT_TO_HEX = ../bit_to_hex.py

# Adjust sources
RTL = ../top_wrapper.v custom_instruction_and_peripheral.sv ../primitive_wrappers.v
TOP = top_wrapper
DESIGN_NAME = custom_instruction_and_peripheral

# Include base Makefile
include ../makefile.include
