// SPDX-FileCopyrightText: © 2026 Leo Moser
// SPDX-License-Identifier: Apache-2.0

(* blackbox, keep *)
module OBI_PERIPHERAL (
    output REQ,
    output WE,
    
    output BE0,
    output BE1,
    output BE2,
    output BE3,
    
    output ADDR0,
    output ADDR1,
    output ADDR2,
    output ADDR3,
    output ADDR4,
    output ADDR5,
    output ADDR6,
    output ADDR7,
    output ADDR8,
    output ADDR9,
    output ADDR10,
    output ADDR11,
    output ADDR12,
    output ADDR13,
    output ADDR14,
    output ADDR15,
    output ADDR16,
    output ADDR17,
    output ADDR18,
    output ADDR19,
    output ADDR20,
    output ADDR21,
    output ADDR22,
    output ADDR23,

    output WDATA0,
    output WDATA1,
    output WDATA2,
    output WDATA3,
    output WDATA4,
    output WDATA5,
    output WDATA6,
    output WDATA7,
    output WDATA8,
    output WDATA9,
    output WDATA10,
    output WDATA11,
    output WDATA12,
    output WDATA13,
    output WDATA14,
    output WDATA15,
    output WDATA16,
    output WDATA17,
    output WDATA18,
    output WDATA19,
    output WDATA20,
    output WDATA21,
    output WDATA22,
    output WDATA23,
    output WDATA24,
    output WDATA25,
    output WDATA26,
    output WDATA27,
    output WDATA28,
    output WDATA29,
    output WDATA30,
    output WDATA31,
    
    input  GNT,
    input  RVALID,
    
    input  RDATA0,
    input  RDATA1,
    input  RDATA2,
    input  RDATA3,
    input  RDATA4,
    input  RDATA5,
    input  RDATA6,
    input  RDATA7,
    input  RDATA8,
    input  RDATA9,
    input  RDATA10,
    input  RDATA11,
    input  RDATA12,
    input  RDATA13,
    input  RDATA14,
    input  RDATA15,
    input  RDATA16,
    input  RDATA17,
    input  RDATA18,
    input  RDATA19,
    input  RDATA20,
    input  RDATA21,
    input  RDATA22,
    input  RDATA23,
    input  RDATA24,
    input  RDATA25,
    input  RDATA26,
    input  RDATA27,
    input  RDATA28,
    input  RDATA29,
    input  RDATA30,
    input  RDATA31
);

endmodule
